# Generated by Django 4.2 on 2023-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_tag_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="main.tag"
            ),
        ),
    ]
